language: go
go:
- '1.9'

before_install:
  - curl -L -o /tmp/dep-linux-amd64 https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 && install -m 0755 /tmp/dep-linux-amd64 $GOPATH/bin/dep

# install: dep ensure -vendor-only
script:
  - "! gofmt -l . | grep ."
  - go test -v ./...
